# Generated by Django 4.0.3 on 2022-03-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(choices=[('one', 'One 1'), ('two', 'Two 2'), ('three', 'Three 3'), ('four', 'Four 4'), ('five', 'Five 5')], max_length=10)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField()),
                ('slug', models.SlugField()),
                ('rate', models.FloatField()),
                ('description1', models.CharField(max_length=30)),
                ('description2', models.CharField(blank=True, max_length=30, null=True)),
                ('description3', models.CharField(blank=True, max_length=30, null=True)),
                ('description4', models.CharField(blank=True, max_length=30, null=True)),
                ('description5', models.CharField(blank=True, max_length=30, null=True)),
                ('description6', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='deposit', max_length=20, null=True)),
                ('amount', models.FloatField(default=0)),
                ('wallest_add', models.CharField(blank=True, max_length=200, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('tid', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('can_withdraw', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Tweak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geng', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
