# Generated by Django 4.0.3 on 2022-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_transactions_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, default='Processing', max_length=20, null=True),
        ),
    ]
