# Generated by Django 4.0.3 on 2022-03-30 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=12, help_text='Calculated crypto amount for fiat', max_digits=17),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=2, help_text='Fiat amount', max_digits=9),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='fiat_currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='paid_crypto_amount',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Paid crypto amount', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrencypayment',
            name='tx_hash',
            field=models.CharField(help_text='Transaction ID', max_length=150, null=True),
        ),
    ]
